---
- hosts: db
  ignore_unreachable: yes
  become: yes

  pre_tasks:
    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-server']
        mysql_log_error: /var/log/mysql/mysqld.log
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"
  tasks:
    - name: Install pip
      yum:
        name: python3-pip
        update_cache: yes
        state: present
    - name: Make sure pymysql is present
      pip:
        name: pymysql
        state: present
    - name: Install mysql
      include_role:
        name: mysql
  tags: db_users