pipeline {
  agent any

  environment {
    ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
  }

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }

      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }

      }
    }

    stage('Package') {
      steps {
        script {
          sh 'echo "Package Stage"'
        }

      }
    }

    stage('Deploy') {
      options {
        timeout(time: 5, unit: 'MINUTES')
      }
      steps {
        script {
          sh 'echo "Deploy Stage"'
          sh 'ls -la'
          ansiblePlaybook credentialsId: 'private_key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/uat.yml', playbook: 'playbooks/site.yml'
        }

      }
    }

    stage('Clean Up') {
      steps {
        script {
          sh 'echo "Clean Up Stage"'
        }

      }
    }

  }
}
