pipeline {
  agent any

  parameters {
    string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
  }

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }

      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }

      }
    }

    stage('Package') {
      steps {
        script {
          sh 'echo "Package Stage"'
        }

      }
    }

    stage('Deploy') {
      options {
        timeout(time: 5, unit: 'MINUTES')
      }
      steps {
        script {
          sh 'echo "Deploy Stage"'
          ansiblePlaybook credentialsId: 'private_key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}.yml', playbook: 'playbooks/site.yml'
        }

      }
    }

    stage('Clean Up') {
      steps {
        script {
          sh 'echo "Clean Up Stage"'
        }

        cleanWs(deleteDirs: true)
      }
    }

  }
  environment {
    ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
  }
}