---
- import_playbook: ../static-assignments/common.yml

- name: Include dynamic variables
  hosts: all
  ignore_unreachable: yes
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml

- name: Install PHP on the Jenkins server
  hosts: localhost
  tasks:
    - include_tasks: ../dynamic-assignments/ci-server.yml
  tags: local

  # - name: Webserver assignment
  #  import_playbook: ../static-assignments/uat-webservers.yml


- name: Install Sonarqube
  import_playbook: ../static-assignments/sonarqube.yml
 

- name: Install Artifactory
  import_playbook: ../static-assignments/artifactory.yml

- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
