---
# - hosts: all
# - import_playbook: ../static-assignments/common-del.yml

# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml



# - import_playbook: ../static-assignments/common.yml   



# - name: Include dynamic variables
#   hosts: all
#   tasks:
#     - include_tasks: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml

# - name: Loadbalancers assignment
#   import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required
