---
- import_playbook: ../static-assignments/common.yml

- name: Include dynamic variables
  hosts: all
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml

- name: Install PHP on the Jenkins server
  hosts: localhost
  tasks:
    - include_tasks: ../dynamic-assignments/ci-server.yml

- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml

- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
