---
# - hosts: all
# - import_playbook: ../static-assignments/common-del.yml

# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml


<<<<<<< HEAD
#- import_playbook: ../static-assignments/common.yml   
=======
# - import_playbook: ../static-assignments/common.yml   
>>>>>>> 2b8e3f7d79b8ce9dc400262bd1a6c16fdede8a16


# - name: Include dynamic variables
#   hosts: all
#   tasks:
#     - include_tasks: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml

# - name: Loadbalancers assignment
#   import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required
